<a href="https://colab.research.google.com/github/muhxz3/Pandas-Notebook/blob/main/Dataset_summary_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<u>Pandas</u>**

In [1]:
# importing pandas

import pandas as pd

- Loading the csv file using pd

In [2]:
data = pd.read_csv('Day7_Student_Dataset.csv')
data

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

**Inspecting First and last rows**

In [3]:
# displays top 5 rows

data.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [4]:
# displays top 10 rows

data.head(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

In [5]:
# displays bottom 5 rows

data.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [6]:
# displays bottom 7 rows

data.tail(7)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

**view random samples**

In [10]:
data.sample(10) # viewing random 10 samples

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad

**checking shape of the dataset**

In [11]:
data.shape

(25, 7)

**checking columns**

In [12]:
data.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

**checking index**

In [14]:
data.index

RangeIndex(start=0, stop=25, step=1)

**Checking data types**

In [16]:
data.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

**Use of .info()**

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

**Use of .describe()**

In [18]:
data.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

**Number of rows and columns in the dataset**<br>
- .shape function returns the rows and cols in the format (rows,cols)

In [19]:
data.shape

(25, 7)

**Displaying the features of the dataset**<br>Use of .columns function

In [22]:
data.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

**Displaying the datatypes of each feature/column**<br>Use of .dtypes

In [24]:
data.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

**Analyzing missing values using .isna() or isnull()**
- .sum() can be used to find the number of missing values

In [25]:
data.isna()

    Student_ID   Name    Age  Course  Marks  Attendance_Percentage   City
0        False  False  False   False  False                  False  False
1        False  False  False   False  False                  False  False
2        False  False  False   False  False                  False  False
3        False  False  False   False  False                  False  False
4        False  False  False   False  False                  False  False
5        False  False  False   False  False                  False  False
6        False  False  False   False  False                  False  False
7        False  False  False   False  False                   True  False
8        False  False  False   False  False                  False  False
9        False  False  False   False  False                  False  False
10       False  False  False   False  False                  False  False
11       False  False  False   False  False                  False  False
12       False  False  False   False  False                  False  False
13       False  False  False   False  False                  False   True
14       False  False  False   False  False                  False  False
15       False  False  False   False  False                  False  False
16       False  False  False   False  False                  False  False
17       False  False  False   False  False                  False  False
18       False  False  False   False   True                  False  False
19       False  False  False   False  False                  False  False
20       False  False  False   False  False                  False  False
21       False  False  False   False  False                  False  False
22       False  False  False   False  False                  False  False
23       False  False  False   False  False                  False  False
24       False  False  False   False  False                  False  False

In [26]:
data.isnull()

    Student_ID   Name    Age  Course  Marks  Attendance_Percentage   City
0        False  False  False   False  False                  False  False
1        False  False  False   False  False                  False  False
2        False  False  False   False  False                  False  False
3        False  False  False   False  False                  False  False
4        False  False  False   False  False                  False  False
5        False  False  False   False  False                  False  False
6        False  False  False   False  False                  False  False
7        False  False  False   False  False                   True  False
8        False  False  False   False  False                  False  False
9        False  False  False   False  False                  False  False
10       False  False  False   False  False                  False  False
11       False  False  False   False  False                  False  False
12       False  False  False   False  False                  False  False
13       False  False  False   False  False                  False   True
14       False  False  False   False  False                  False  False
15       False  False  False   False  False                  False  False
16       False  False  False   False  False                  False  False
17       False  False  False   False  False                  False  False
18       False  False  False   False   True                  False  False
19       False  False  False   False  False                  False  False
20       False  False  False   False  False                  False  False
21       False  False  False   False  False                  False  False
22       False  False  False   False  False                  False  False
23       False  False  False   False  False                  False  False
24       False  False  False   False  False                  False  False

In [27]:
data.isna().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [28]:
data.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64