<a href="https://colab.research.google.com/github/muhxz3/Pandas-Notebook/blob/main/Pandas_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Library**
<br>


*   It is used to work with datasets using python
*   Pandas - Panel data or Python Data Analysis

In [40]:
# importing pandas
import pandas as pd

It has two types of data
<br>

1.   Series - It is a single column or like a 1D array
2.   Data Frame - a table where data is stored in the form of rows and columns

**Creating Series**

In [41]:
a = [1,2,3,4,5]
s = pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

**Index Labels**

In [42]:
s = pd.Series(a, index = ['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

**DataFrame from a Dictionary**

In [43]:
cars = {
    "name": ["BMW","Audi","MG","Benz"],
    "rating": [8,7,4,9]
}

s = pd.DataFrame(cars)
print(s)

   name  rating
0   BMW       8
1  Audi       7
2    MG       4
3  Benz       9

**Series from a Dictionary**

In [44]:
python_score = {"Muhaz": 24, "Riya": 30, "Arun": 32}
s = pd.Series(python_score)
print(s)

Muhaz    24
Riya     30
Arun     32
dtype: int64

**Key Observation:** Use dictionary itself while creating a series to have desired index labels.

**Series Basic Operations**

In [45]:
s = pd.Series(
    [10,20,30],
    index = ['a','b','c']
)

print(s*2)

a    20
b    40
c    60
dtype: int64

In [46]:
s2 = pd.Series(
    [1,2,3],
    index = ['b','c','d']
)

print(s + s2)

a     NaN
b    21.0
c    32.0
d     NaN
dtype: float64

**DataFrame from a numpy arrays**

In [47]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
df = pd.DataFrame(a, columns = ['DS','DA'])
print(df)

   DS  DA
0   1   2
1   3   4
2   5   6

DataFrame -> numpy array

In [48]:
print(df.to_numpy())

[[1 2]
 [3 4]
 [5 6]]

**Type() function**

In [49]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

**Working with Data Files**

In [50]:
# .csv - comma separated values

# load data in python code
data = pd.read_csv("Day7_Student_Dataset.csv")
data

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [51]:
data.head() # gets top 5 rows

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [52]:
data.head(3) # gets top 3 rows

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai

In [53]:
data.tail() # bottom 5 rows

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [54]:
data.tail(7) # bottom 7 rows

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [55]:
data.sample() # random 5 rows

    Student_ID         Name  Age Course  Marks  Attendance_Percentage     City
19        1020  Priya Menon   21     AI   90.0                   91.0  Chennai

**Key Parameters associated with read_csv()**

1. sep - tells the pandas what separates values.

In [56]:
df = pd.read_csv("Day7_Student_Dataset.csv", sep = "\t")
df

   Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0   1001,Aarav Sharma,19,Data Science,87.0,91.0,Sr...
1                1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2   1003,Rohan Mehta,18,Computer Science,76.0,82.0...
3   1004,Ananya Singh,21,Data Science,81.0,88.0,Sr...
4              1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5   1006,Ishita Gupta,20,Computer Science,88.0,93....
6    1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7               1008,Sara Ahmed,19,AI,73.0,,Hyderabad
8   1009,Arjun Nair,18,Computer Science,84.0,86.0,...
9   1010,Mehak Bhat,21,Data Science,79.0,90.0,Srin...
10          1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11  1012,Aisha Mir,19,Computer Science,68.0,72.0,D...
12   1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13                   1014,Sana Malik,18,AI,89.0,92.0,
14  1015,Karan Joshi,20,Computer Science,77.0,85.0...
15  1016,Hiba Sheikh,21,Data Science,94.0,96.0,Sri...
16           1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17  1018,Manya Rao,22,Computer Science,70.0,74.0,B...
18      1019,Yusuf Dar,20,Data Science,,87.0,Srinagar
19           1020,Priya Menon,21,AI,90.0,91.0,Chennai
20  1021,Aman Kumar,18,Computer Science,74.0,78.0,...
21  1022,Alina Shah,19,Data Science,96.0,98.0,Srin...
22              1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23  1024,Maryam Khan,20,Computer Science,85.0,88.0...
24  1025,Reyansh Jain,21,Data Science,80.0,84.0,Ko...

2. header()

In [57]:
df = pd.read_csv("Day7_Student_Dataset.csv", header = None)
df

,0,1,2,3,4,5,6
0,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
1,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
2,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
3,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
4,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
5,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
6,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
7,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
8,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
9,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
10,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
11,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
12,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
13,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
14,1014,Sana Malik,18,AI,89.0,92.0,NaN
15,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
16,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
17,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
18,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
19,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
20,1020,Priya Menon,21,AI,90.0,91.0,Chennai
21,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
22,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
23,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
24,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
25,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

3. names()

In [58]:
df = pd.read_csv("Day7_Student_Dataset.csv", names = ['a','b','c','d','e','f','g'])
df

,a,b,c,d,e,f,g
0,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
1,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
2,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
3,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
4,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
5,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
6,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
7,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
8,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
9,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
10,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
11,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
12,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
13,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
14,1014,Sana Malik,18,AI,89.0,92.0,NaN
15,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
16,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
17,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
18,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
19,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
20,1020,Priya Menon,21,AI,90.0,91.0,Chennai
21,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
22,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
23,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
24,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
25,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [59]:
df = pd.read_csv("Day7_Student_Dataset.csv", index_col = "Student_ID")
df

,Name,Age,Course,Marks,Attendance_Percentage,City
Student_ID,,,,,,
1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1002,Zoya Khan,20,AI,92.0,95.0,Delhi
1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
1014,Sana Malik,18,AI,89.0,92.0,NaN
1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
1020,Priya Menon,21,AI,90.0,91.0,Chennai
1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
1023,Nikhil Sood,22,AI,78.0,83.0,Pune
1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

4. usecols()

In [60]:
df = pd.read_csv("Day7_Student_Dataset.csv", usecols = ['Student_ID','Age'])
df

    Student_ID  Age
0         1001   19
1         1002   20
2         1003   18
3         1004   21
4         1005   19
5         1006   20
6         1007   22
7         1008   19
8         1009   18
9         1010   21
10        1011   20
11        1012   19
12        1013   23
13        1014   18
14        1015   20
15        1016   21
16        1017   19
17        1018   22
18        1019   20
19        1020   21
20        1021   18
21        1022   19
22        1023   22
23        1024   20
24        1025   21

**Saving data**<br>
to_csv() and to_excel()

In [61]:
df.to_csv()

',Student_ID,Age\n0,1001,19\n1,1002,20\n2,1003,18\n3,1004,21\n4,1005,19\n5,1006,20\n6,1007,22\n7,1008,19\n8,1009,18\n9,1010,21\n10,1011,20\n11,1012,19\n12,1013,23\n13,1014,18\n14,1015,20\n15,1016,21\n16,1017,19\n17,1018,22\n18,1019,20\n19,1020,21\n20,1021,18\n21,1022,19\n22,1023,22\n23,1024,20\n24,1025,21\n'

In [62]:
df.to_excel("student_age.xlsx", sheet_name = "Students")

In [63]:
df = pd.DataFrame(
    {
        "name": ['A','B','C'],
        "score": [9,6,2]
    }
)

df.to_csv("samplecsv.csv", index = False)

**.shape**
<br>(rows,cols)

In [66]:
df.shape

(3, 2)

In [67]:
data.shape

(25, 7)

**Data Inspection**
<br>
1. .info() - tells the name of all the columns, non-null values and data types

In [68]:
# EDA - Exploratory Data Analysis
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

2. .dtypes - tells the data types of every column

In [70]:
data.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

3. .columns

In [73]:
data.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

4. .index

In [74]:
data.index

RangeIndex(start=0, stop=25, step=1)

5. .describe() - basic statistical features of a dataset

In [75]:
data.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

**Pitfalls**<br>
-  like wrong delimiter(',', ';')

In [77]:
df = pd.read_csv("Day7_Student_Dataset.csv")
print(df.columns)

df = pd.read_csv("Day7_Student_Dataset.csv", sep = ';')
print(df.columns)

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')
Index(['Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City'], dtype='object')

**Header = 0**<br>
**Header = None**

In [79]:
df = pd.read_csv("Day7_Student_Dataset.csv", header = 0)
df

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [80]:
df = pd.read_csv("Day7_Student_Dataset.csv", header = None)
df

,0,1,2,3,4,5,6
0,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
1,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
2,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
3,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
4,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
5,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
6,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
7,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
8,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
9,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
10,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
11,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
12,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
13,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
14,1014,Sana Malik,18,AI,89.0,92.0,NaN
15,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
16,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
17,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
18,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
19,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
20,1020,Priya Menon,21,AI,90.0,91.0,Chennai
21,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
22,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
23,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
24,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
25,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

**Identifying missing values**

In [81]:
df = pd.read_csv("Day7_Student_Dataset.csv")
df.isna()

    Student_ID   Name    Age  Course  Marks  Attendance_Percentage   City
0        False  False  False   False  False                  False  False
1        False  False  False   False  False                  False  False
2        False  False  False   False  False                  False  False
3        False  False  False   False  False                  False  False
4        False  False  False   False  False                  False  False
5        False  False  False   False  False                  False  False
6        False  False  False   False  False                  False  False
7        False  False  False   False  False                   True  False
8        False  False  False   False  False                  False  False
9        False  False  False   False  False                  False  False
10       False  False  False   False  False                  False  False
11       False  False  False   False  False                  False  False
12       False  False  False   False  False                  False  False
13       False  False  False   False  False                  False   True
14       False  False  False   False  False                  False  False
15       False  False  False   False  False                  False  False
16       False  False  False   False  False                  False  False
17       False  False  False   False  False                  False  False
18       False  False  False   False   True                  False  False
19       False  False  False   False  False                  False  False
20       False  False  False   False  False                  False  False
21       False  False  False   False  False                  False  False
22       False  False  False   False  False                  False  False
23       False  False  False   False  False                  False  False
24       False  False  False   False  False                  False  False

In [82]:
df.isnull()

    Student_ID   Name    Age  Course  Marks  Attendance_Percentage   City
0        False  False  False   False  False                  False  False
1        False  False  False   False  False                  False  False
2        False  False  False   False  False                  False  False
3        False  False  False   False  False                  False  False
4        False  False  False   False  False                  False  False
5        False  False  False   False  False                  False  False
6        False  False  False   False  False                  False  False
7        False  False  False   False  False                   True  False
8        False  False  False   False  False                  False  False
9        False  False  False   False  False                  False  False
10       False  False  False   False  False                  False  False
11       False  False  False   False  False                  False  False
12       False  False  False   False  False                  False  False
13       False  False  False   False  False                  False   True
14       False  False  False   False  False                  False  False
15       False  False  False   False  False                  False  False
16       False  False  False   False  False                  False  False
17       False  False  False   False  False                  False  False
18       False  False  False   False   True                  False  False
19       False  False  False   False  False                  False  False
20       False  False  False   False  False                  False  False
21       False  False  False   False  False                  False  False
22       False  False  False   False  False                  False  False
23       False  False  False   False  False                  False  False
24       False  False  False   False  False                  False  False

**Quantifying null values**

In [83]:
df.isna().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [84]:
df.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64